{
 "title": "Sec-Mon Quarantine",
 "panels": [
  {
   "title": "Quarantined IPs",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
   "targets": [
    { "expr": "quarantined_ip_count" }
   ]
  },
  {
   "title": "Suspicious Requests",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(suspicious_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Quarantined Blocks",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 16, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(quarantined_blocks_total[1m]))"
    }
   ]
  }
 ]
}